let myDate = new Date ()
console.log(myDate.toDateString())
console.log(myDate.toDateString())
console.log(myDate.toLocaleDateString())
console.log(myDate.toLocaleString())
console.log(myDate.toJSON())
console.log(typeof(myDate))
let myCreatedDate= new Date()
//  myCreatedDate = new Date.now()
let timestamp = Date.now()
console.log(timestamp.toLocaleString())